// <auto-generated />
using System;
using Insurance.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Insurance.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Insurance.Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeNextBirthday")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DeathSumInsured")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyPremium")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OccupationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OccupationId");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Insurance.Domain.Entities.Occupation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OccupationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RatingFactor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("occupations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OccupationName = "Cleaner",
                            Rating = "Light Manual",
                            RatingFactor = 1.50m
                        },
                        new
                        {
                            Id = 2,
                            OccupationName = "Doctor",
                            Rating = "Professional",
                            RatingFactor = 1.50m
                        },
                        new
                        {
                            Id = 3,
                            OccupationName = "Author",
                            Rating = "White Collar",
                            RatingFactor = 2.25m
                        },
                        new
                        {
                            Id = 4,
                            OccupationName = "Farmer",
                            Rating = "Heavy Manual",
                            RatingFactor = 3.75m
                        },
                        new
                        {
                            Id = 5,
                            OccupationName = "Mechanic",
                            Rating = "Heavy Manual",
                            RatingFactor = 3.75m
                        },
                        new
                        {
                            Id = 6,
                            OccupationName = "Florist",
                            Rating = "Light Manual",
                            RatingFactor = 1.50m
                        },
                        new
                        {
                            Id = 7,
                            OccupationName = "Other",
                            Rating = "Heavy Manual",
                            RatingFactor = 3.75m
                        });
                });

            modelBuilder.Entity("Insurance.Domain.Entities.Member", b =>
                {
                    b.HasOne("Insurance.Domain.Entities.Occupation", "Occupation")
                        .WithMany()
                        .HasForeignKey("OccupationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Occupation");
                });
#pragma warning restore 612, 618
        }
    }
}
